export default function About(){
    return(
        <div className="flex justify-center">
            <p className="w-1/2 items-center">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique senectus et netus et malesuada. Pellentesque habitant morbi tristique senectus et netus et. Consectetur adipiscing elit duis tristique sollicitudin nibh. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Tellus id interdum velit laoreet id donec ultrices. Tristique senectus et netus et malesuada fames ac turpis. Sagittis aliquam malesuada bibendum arcu vitae. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Neque ornare aenean euismod elementum nisi. Pretium aenean pharetra magna ac. Id aliquet lectus proin nibh. Cursus in hac habitasse platea. Lectus nulla at volutpat diam ut venenatis tellus in. Eget duis at tellus at urna. Risus feugiat in ante metus dictum at tempor commodo. Placerat orci nulla pellentesque dignissim enim sit. Id faucibus nisl tincidunt eget nullam non nisi. Nisl nunc mi ipsum faucibus.

Ut faucibus pulvinar elementum integer. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Nulla facilisi cras fermentum odio. At lectus urna duis convallis convallis. Massa tincidunt dui ut ornare lectus sit amet. Consectetur adipiscing elit duis tristique. Velit egestas dui id ornare arcu odio ut sem. Tempor id eu nisl nunc. Morbi tristique senectus et netus. Eget nullam non nisi est sit amet. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero.

Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Elit pellentesque habitant morbi tristique senectus et netus et. Purus gravida quis blandit turpis cursus. Sem integer vitae justo eget magna fermentum. Dui ut ornare lectus sit amet est placerat. Duis ultricies lacus sed turpis tincidunt id aliquet. Arcu felis bibendum ut tristique et egestas quis ipsum. Est velit egestas dui id ornare arcu. Aenean sed adipiscing diam donec adipiscing tristique. Odio tempor orci dapibus ultrices in iaculis nunc sed. Orci nulla pellentesque dignissim enim sit amet venenatis urna cursus. Elementum nibh tellus molestie nunc non blandit. Est sit amet facilisis magna. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam. Commodo elit at imperdiet dui accumsan. Tincidunt tortor aliquam nulla facilisi cras. Egestas diam in arcu cursus. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus.

Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Elementum eu facilisis sed odio. Ut ornare lectus sit amet. Sit amet luctus venenatis lectus. Odio euismod lacinia at quis. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Sit amet purus gravida quis blandit turpis. Pharetra pharetra massa massa ultricies mi quis. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam. Vitae elementum curabitur vitae nunc sed. Aliquet sagittis id consectetur purus ut faucibus pulvinar. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Facilisi nullam vehicula ipsum a arcu cursus vitae. Sed nisi lacus sed viverra tellus in hac habitasse. Quis ipsum suspendisse ultrices gravida dictum. Lacus laoreet non curabitur gravida arcu. Pharetra convallis posuere morbi leo urna molestie at elementum eu.

Aenean euismod elementum nisi quis eleifend. Tristique senectus et netus et malesuada fames. Laoreet sit amet cursus sit amet dictum sit amet. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices dui. Nisi est sit amet facilisis magna etiam. Nunc sed augue lacus viverra vitae congue eu consequat ac. Viverra vitae congue eu consequat ac felis donec et. Lacus vestibulum sed arcu non odio. Euismod nisi porta lorem mollis aliquam ut porttitor. Egestas congue quisque egestas diam. Diam sit amet nisl suscipit adipiscing bibendum est ultricies. Duis convallis convallis tellus id interdum velit. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae. Eu lobortis elementum nibh tellus molestie nunc non blandit. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Id cursus metus aliquam eleifend mi. Tincidunt tortor aliquam nulla facilisi cras fermentum odio.
                </p>
        </div>
    )
}